name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点执行（北京时间 8 点）
  workflow_dispatch:     # 手动触发选项（可选）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取上游代码
        uses: actions/checkout@v4
        with:
          ref: main  # 你的默认分支名（如 master/main）

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/AlistGo/alist.git
          git fetch upstream

      - name: 合并更新
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
